### ISSUE TITLE
Ошибка в файле APS/Labs/3. Register file and memory/board files/README.md в ветке ПИН

### ISSUE THREAD

**Issue by IgorKolesov** [MPSU/exAPS#135]
В тексте после описания, как выставить введенный адрес на какой-то из входов адреса, идет абзац "После выставления адресов, можно переключатели можно использовать в качестве ввода первых шестнадцати бит данных. Для записи введенных данных по адресу A3 используется кнопка BTND, для чтения данных по адресам A1, A2 (с выводом результатов чтения на семисегментные индикаторы) используется кнопка BTNU."  В первом предложении есть 2 слова "можно"

**Comment by HepoH3** [comment]
Закинул бонус в ориокс, спасибо!
