### ISSUE TITLE
исправить схему 4битного сумматора в методичке сумматора

### ISSUE THREAD

**Issue by HepoH3** [MPSU/exAPS#15]

**Comment by gr33nka** [comment]
У тебя исходники, и вообще удобнее, исправишь в technical картинку?

**Comment by HepoH3** [comment]
Исправлено в [6793715](https://github.com/MPSU/APS/commit/6793715bf4576f8c9b9b1e9fa97ae33001d3a061) (осталось проверить, что в остальных ветках ссылаются на техническую)

**Comment by gr33nka** [comment]
Других вариантов вроде и не было
