### ISSUE TITLE
Ошибка в тексте ЛАБ4 ветка ПИН

### ISSUE THREAD

**Issue by IgorKolesov** [MPSU/exAPS#152]
https://github.com/MPSU/APS/blob/%D0%9F%D0%98%D0%9D/Labs/4.%20Primitive%20programmable%20device/README.md#%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D0%B9

**Кодирование вычислительных инструкций**
Абзац начинается с: "Чтобы добавить поддержку **### каких-либо инструкции**...". 
Нужно исправить на "какой-либо инструкции" или "каких-либо инструкций"

Колесов ПИН-33

**Comment by HepoH3** [comment]
Исправил, спасибо!
