### ISSUE TITLE
Ошибка в тексте Lab6, ветка ПИН

### ISSUE THREAD

**Issue by ANTONINIK** [MPSU/exAPS#174]
https://github.com/MPSU/APS/tree/%D0%9F%D0%98%D0%9D/Labs/6.%20Datapath#:~:text=%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%20%D0%BD%D1%83%D0%BC%D0%B5%D1%80%D1%83%D1%8E%D1%82%D1%81%D1%8F%20%D1%81%D0%BB%D0%B5%D0%B2%D0%B0%20%D0%BD%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%20%D0%BE%D1%82%20%D0%BC%D0%BB%D0%B0%D0%B4%D1%88%D0%B5%D0%B3%D0%BE%20%D0%BA%20%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B5%D0%BC%D1%83%2C%20%D0%BE%D0%B4%D0%BD%D0%B0%D0%BA%D0%BE%20%D1%80%D0%B0%D0%B7%D1%80%D1%8F%D0%B4%D1%8B%20%D1%81%D1%87%D0%B8%D1%82%D0%B0%D1%8E%D1%82%D1%81%D1%8F%20%D0%BD%D0%B0%D0%BE%D0%B1%D0%BE%D1%80%D0%BE%D1%82%3A%20%D1%81%D0%BB%D0%B5%D0%B2%D0%B0%2D%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%20%D0%BE%D1%82%20%D0%BC%D0%BB%D0%B0%D0%B4%D1%88%D0%B5%D0%B3%D0%BE%20%D0%BA%20%D1%81%D1%82%D0%B0%D1%80%D1%88%D0%B5%D0%BC%D1%83.

Ошибка в следующем предложении: "Слова нумеруются слева на право от младшего к старшему, однако разряды считаются наоборот: слева-направо от младшего к старшему."

Марьянский Антон ПИН-33

**Comment by HepoH3** [comment]
Исправлено в 99b3c91.
