### ISSUE TITLE
8 лабораторная работа (ПИН)

### ISSUE THREAD

**Issue by coIorbIind** [MPSU/exAPS#179]
В тексте написано, что правый столбец у Stack pointer должен быть пустым, а в нем написано "Callee", а с Thread pointer ситуация обратная <img width="792" alt="image" src="https://github.com/MPSU/APS/assets/91391687/36d3682e-bacb-46f7-97fe-1d705419f085">

**Comment by HepoH3** [comment]
Исправлено в [d2062ef](https://github.com/MPSU/APS/commit/d2062ef573915c6e109b1a0696f5535264118a0f)
Напиши фамилию и группу, чтоб я мог проставить доп баллы

**Comment by coIorbIind** [comment]
Соболе

> Исправлено в [d2062ef](https://github.com/MPSU/APS/commit/d2062ef573915c6e109b1a0696f5535264118a0f) Напиши фамилию и группу, чтоб я мог проставить доп баллы

Соболев ПИН-33
