### ISSUE TITLE
Исправить пикчу таблицы операций алу

### ISSUE THREAD

**Issue by HepoH3** [MPSU/exAPS#29]
$signed (A<B) вводит студентов в заблуждение.

**Comment by gr33nka** [comment]
Заменить в таблице на `$signed(A) < $signed(B)`?

**Comment by HepoH3** [comment]
Угуу

**Comment by HepoH3** [comment]
Можно в целом пикчу на сырую таблицу заменить.

**Comment by gr33nka** [comment]
Кстати да, можно. Доделываю 4-ую лабу и следом поправлю таблицу, все будет сегодня

**Comment by gr33nka** [comment]
Нуууу, поставил пока только у ИВТ. Думаешь надо продолжать? Или картинку поменять? Нужно сторонне мнение. Можно конечно голосовалку в обсуждениях запилить, но я боюсь узнать количество людей, которые будут участвовать в голосовании)

**Comment by HepoH3** [comment]
Блин, с утра с телефона посмотрел, решил что надо сперва еще глянуть на компе — а потом ответить, и забыл. Короче мне лично нравится, да и я в целом топлю за то, чтобы по-максимуму перегнать все пикчи в текст, где это можно.

**Comment by gr33nka** [comment]
Готово!
