### ISSUE TITLE
ЛР 6 для ИВТ. Неправильное сравнение с mcause в программе из примера

### ISSUE THREAD

**Issue by gr33nka** [MPSU/exAPS#48]
### Discussed in https://github.com/MPSU/APS/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **BROsandr** December  7, 2022</sup>
![image](https://user-images.githubusercontent.com/53278658/206222256-daded977-acbb-49ea-8b9f-7e312a761cf1.png)
mcause сравнивается с 5ю, но сам mcause формируется с 1 в старшем бите.
![image](https://user-images.githubusercontent.com/53278658/206222715-2b1e0953-5b39-4e8e-83cf-fb0a7e1cc32d.png)
Поэтому программа прерывания не обнаруживает</div>

**Comment by HepoH3** [comment]
Не актуально в новой [методичке](https://github.com/MPSU/APS-reborn/tree/master/Labs/10.%20Interrupt%20subsystem), которая в какой-то момент будет портирована в этот репозиторий.
