### ISSUE TITLE
ЛР 6 для ИВТ. Ошибка на рисунке реализации CSR

### ISSUE THREAD

**Issue by gr33nka** [MPSU/exAPS#49]
### Discussed in https://github.com/MPSU/APS/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **BROsandr** November 25, 2022</sup>
Правильно ли я понимаю, что есть опечатка в методичке, и операнды в выражении нужно поменять, чтобы привести выражение в соотсетствие со схемой
![image](https://user-images.githubusercontent.com/53278658/204056457-3c1bc552-4b76-46cb-8dfe-ab85f3e42388.png)
</div>

**Comment by HepoH3** [comment]
Не актуально в новой [методичке](https://github.com/MPSU/APS-reborn/tree/master/Labs/10.%20Interrupt%20subsystem), которая в какой-то момент будет портирована в этот репозиторий.
