### ISSUE TITLE
битая ссылка в lab6 ПИН

### ISSUE THREAD

**Issue by HepoH3** [MPSU/exAPS#56]
см в Более подробно о [RV32I](https://github.com/MPSU/APS/blob/%D0%9F%D0%98%D0%9D/Other/RV32I.md).

**Comment by gr33nka** [comment]
Поправил

**Comment by HepoH3** [comment]
возможно в остальных ветках та же штука, пока времени нет, набираю таски чтоб потом пачкой закрыть
