### ISSUE TITLE
Ошибка ЛР5 файл pdf. Описание miriscv_lsu

### ISSUE THREAD

**Issue by okuroshi** [MPSU/exAPS#58]
В описание блока присутствуют синтаксические ошибки
output [31:0] lsu_data_o (пропущена запятая)
output [31:0] data_wdata_o (лишняя запятая)

**Comment by HepoH3** [comment]
Отпишись в телеграм по поводу доп балла.

**Comment by HepoH3** [comment]
Не актуально в новой [методичке](https://github.com/MPSU/APS-reborn/tree/master/Labs/08.%20Load-store%20unit), которая в какой-то момент будет портирована в этот репозиторий.
