### ISSUE TITLE
Ошибка в адресе устройства лр 7

### ISSUE THREAD

**Issue by MrShelDie** [MPSU/exAPS#72]
По-моему, в адресе четвёртого периферийного устройства ошибка (стр. 2 и 3)
![image](https://user-images.githubusercontent.com/65782143/211372154-1b39c8d5-7d85-48c0-b1bb-7d19dde9e206.png)
![image](https://user-images.githubusercontent.com/65782143/211372272-0236c7c8-fe74-4a0c-8ffd-dff339ecb7a9.png)

**Comment by HepoH3** [comment]
Все так, спасибо!
