### ISSUE TITLE
Ошибка в файле Modules.md

### ISSUE THREAD

**Issue by coIorbIind** [MPSU/exAPS#93]
<img width="1013" alt="2023-02-11_22-45-38" src="https://user-images.githubusercontent.com/91391687/218278205-033af9bb-73ae-47b5-9768-254177598652.png">

Ошибка в описании логической операции

**Comment by HepoH3** [comment]
Напиши фамилию и группу, чтоб можно было поставить доп баллы

**Comment by coIorbIind** [comment]
Соболев ПИН-33
